#!/usr/bin/env python3
"""Locate (and remember) the Infinigen conda env, so scripts don't hardcode a
machine-specific path like /home/jinnyeong/miniconda3/...

Resolution order for the env's python:
  1. $INFINIGEN_PYTHON
  2. the local config file  <repo>/.infinigen_env  (machine-local, git-ignored)
  3. auto-detect (common conda layouts, /home/* globs, `conda env list`)

When found by auto-detect, the path is PERSISTED to <repo>/.infinigen_env as a
shell-sourceable `export INFINIGEN_PYTHON=...` line, so both the Python wrapper
(infinigen_gen.py) and the Bash importer (run_infinigen_import.sh) pick it up.

CLI:
  python scripts/infinigen_env.py            # print resolved python (auto-persist)
  python scripts/infinigen_env.py --export   # print shell `export ...` lines
  python scripts/infinigen_env.py --prompt    # ask if not found, then save
  python scripts/infinigen_env.py --write     # detect+persist, print path (quiet-ish)
"""

from __future__ import annotations

import glob
import os
import shutil
import subprocess
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
CONFIG = REPO / ".infinigen_env"


# --- config file (shell-sourceable: `export KEY="VALUE"`) ------------------

def read_config() -> dict:
    cfg: dict[str, str] = {}
    if CONFIG.exists():
        for line in CONFIG.read_text(encoding="utf-8").splitlines():
            line = line.strip()
            if not line or line.startswith("#") or "=" not in line:
                continue
            if line.startswith("export "):
                line = line[len("export "):]
            k, _, v = line.partition("=")
            cfg[k.strip()] = v.strip().strip('"').strip("'")
    return cfg


def write_config(python: Path | str | None = None, dirpath: Path | str | None = None) -> None:
    cfg = read_config()
    if python:
        cfg["INFINIGEN_PYTHON"] = str(Path(python).expanduser())
    if dirpath:
        cfg["INFINIGEN_DIR"] = str(Path(dirpath).expanduser())
    lines = ["# auto-generated by scripts/infinigen_env.py — machine-local, do not commit"]
    lines += [f'export {k}="{v}"' for k, v in cfg.items()]
    CONFIG.write_text("\n".join(lines) + "\n", encoding="utf-8")


# --- detection -------------------------------------------------------------

_CONDA_BASES = ["miniconda3", "anaconda3", "miniforge3", "mambaforge"]


def _python_candidates():
    yield os.environ.get("INFINIGEN_PYTHON")
    yield read_config().get("INFINIGEN_PYTHON")
    for base in _CONDA_BASES:
        yield Path.home() / base / "envs" / "infinigen" / "bin" / "python"
    yield Path("/opt/conda/envs/infinigen/bin/python")
    for pat in ("/home/*/miniconda3/envs/infinigen/bin/python",
                "/home/*/anaconda3/envs/infinigen/bin/python",
                "/home/*/miniforge3/envs/infinigen/bin/python"):
        yield from (Path(p) for p in glob.glob(pat))
    conda = shutil.which("conda")
    if conda:
        try:
            out = subprocess.run([conda, "env", "list"], capture_output=True,
                                 text=True, timeout=15).stdout
            for line in out.splitlines():
                line = line.strip()
                if not line or line.startswith("#"):
                    continue
                path = line.split()[-1]
                if Path(path).name == "infinigen":
                    yield Path(path) / "bin" / "python"
        except Exception:
            pass


def _dir_candidates():
    yield os.environ.get("INFINIGEN_DIR")
    yield read_config().get("INFINIGEN_DIR")
    yield Path.home() / "module" / "infinigen"
    for pat in ("/home/*/module/infinigen", "/home/*/infinigen"):
        yield from (Path(p) for p in glob.glob(pat))


def _first_existing(cands, *, isdir=False):
    for c in cands:
        if not c:
            continue
        p = Path(c).expanduser()
        if (p.is_dir() if isdir else p.exists()):
            return p
    return None


def resolve_python(*, prompt: bool = False, persist: bool = True) -> Path:
    p = _first_existing(_python_candidates())
    if p is None and prompt:
        try:
            ans = input("infinigen env python 경로를 입력하세요 "
                        "(예: /home/<user>/miniconda3/envs/infinigen/bin/python): ").strip()
        except EOFError:
            ans = ""
        cand = Path(ans).expanduser() if ans else None
        if cand and cand.exists():
            p = cand
        else:
            raise SystemExit(f"[infinigen_env] 경로를 찾을 수 없습니다: {ans!r}")
    if p is None:
        raise FileNotFoundError(
            "infinigen env python을 찾지 못했습니다. $INFINIGEN_PYTHON 를 설정하거나 "
            "`python scripts/infinigen_env.py --prompt` 로 경로를 등록하세요.")
    if persist:
        write_config(python=p, dirpath=_first_existing(_dir_candidates(), isdir=True))
    return p


def resolve_dir() -> Path | None:
    return _first_existing(_dir_candidates(), isdir=True)


def main() -> int:
    import argparse
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--export", action="store_true", help="print shell export lines")
    ap.add_argument("--prompt", action="store_true", help="ask for the path if not found")
    ap.add_argument("--write", action="store_true", help="detect+persist (default also persists)")
    a = ap.parse_args()
    try:
        py = resolve_python(prompt=a.prompt, persist=True)
    except (FileNotFoundError, SystemExit) as e:
        print(str(e))
        return 1
    d = resolve_dir()
    if a.export:
        print(f'export INFINIGEN_PYTHON="{py}"')
        if d:
            print(f'export INFINIGEN_DIR="{d}"')
    elif a.write:
        print(py)
    else:
        print(f"INFINIGEN_PYTHON = {py}")
        print(f"INFINIGEN_DIR    = {d or '(not found; using default)'}")
        print(f"saved to {CONFIG.relative_to(REPO)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
